# Generated by Django 4.2.1 on 2023-09-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AudioResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Audio Resource',
                'verbose_name_plural': 'Audio Resources',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='TextResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveIntegerField()),
                ('to_object_id', models.PositiveIntegerField()),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relation', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relation', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('textresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.textresource')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('second_brain.textresource',),
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('videoresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.videoresource')),
                ('video_id', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('second_brain.videoresource',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('episodes', models.ManyToManyField(blank=True, to='second_brain.podcastepisode')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('textresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.textresource')),
                ('subtitle', models.CharField(blank=True, max_length=128)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('authors', models.ManyToManyField(blank=True, null=True, to='second_brain.author')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('second_brain.textresource',),
        ),
    ]
