# Generated by Django 4.2.1 on 2023-06-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_brain', '0002_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Audio Resource',
                'verbose_name_plural': 'Audio Resources',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
            },
            bases=('second_brain.resource',),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='second_brain.resource')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('episodes', models.ManyToManyField(blank=True, to='second_brain.podcastepisode')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('second_brain.resource',),
        ),
    ]
