# Generated by Django 4.2.1 on 2023-06-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_brain', '0003_audioresource_podcastepisode_podcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcasts'},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='second_brain.author'),
        ),
    ]
