# Generated by Django 4.2.1 on 2023-06-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_brain', '0004_alter_podcast_options_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
