# Generated by Django 4.2.1 on 2023-08-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('second_brain', '0006_relation_relationscontainer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationscontainer',
            unique_together={('content_type', 'object_id')},
        ),
    ]
