# Generated by Django 4.2.1 on 2023-09-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_brain', '0006_relation_relationscontainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationsContainer',
        ),
    ]
